### ISSUE TITLE
New designs

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/devtools#159]
We've been working on the current visuals for over a year now, and adding to it incrementally. Now that we have a larger collection of features it might be worth going back to the drawing board, and see if there is a better design to house some of these new features.

If anyone else has any thoughts or critiques about the current design this might be a good place to hang those for consideration.

@shixiedesign has been super helpful and already proposed a couple awesome ideas. See comment below for more of her contributions.

#### Features coming to consider

- [ ] Settings per tab #26 
- [ ] Color and opacity #52 
- [ ] what's new #85 
- [ ] issues and documentation #39, #20
- [ ] components by library #21

**Comment by photodow** [comment]
From @shixiedesign 

> Hey @james.dow I’ve been trying to give you more detailed feedbacks but only got to do 3 screens today!
>
> ![image](https://user-images.githubusercontent.com/3793636/139959071-2ff706e7-44c7-4f08-a29f-14428e335646.png)
> 
> In summary I think simplifying the number of different UX models could help. Toggle or checkbox is one. Some toggles seem unnecessary. I did a few explorations. Also not very complete! Welcome feedback:
> 
> ![image](https://user-images.githubusercontent.com/3793636/139959011-c2cf0903-87ee-408b-9fcc-2175f9e7509e.png)
> 
> There’s potentially too much in page info. We can see if there are feedback for dropping a few things. Maybe it’s okay as is. The only down side is the scroll is pretty long.
