### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/devtools#160]
### Summary

With the coming of Carbon v11 it might be good to put a plan together to release version 3 of the tool. Here are some items we could explore adding to make that wortwhile.

#### Must haves
- [ ] Carbon v11 support #158 
- [ ] Versioned tokens #6 
- [ ] New designs #159

#### Stretch goals
Some of these could even could come before v11. I mostly include most of them here to be thought about in the #159 redesign.

- [ ] Settings per tab #26 
- [ ] Color and opacity #52 
- [ ] what's new #85 
- [ ] issues and documentation #39, #20
- [ ] shortcut revamp #127 
- [ ] components by library #21
