### ISSUE TITLE
Separate carbon global variables from extension and version them

### ISSUE THREAD

**Issue by photodow** [carbon-design-system/devtools#6]
### versioning carbon
The use of carbon to analyze a page requires variables from built by their npm packages. If they change a value in the slightest the spec identifier will come back with not found. If we can provide an option of historic Carbon versions the user can choose from then they can compare against their version in use. It should of course remind them / ding them for using an outdated version, but at least teams can be aligned that they are aligned based on their version.

### seperation of concerns
With so many versions on something like a CDN we also take a good chunk of code out of the extension itself and avoid resubmitting the extension every time Carbon makes an update which is a huge time suck on this project.

### automate and scale
As a side note if we can get system teams like Carbon, Security, Cloud Pal, and IBM.com to add their version of carbon as a global variable we might be able to autodetect the version to use as well.

### Todo...
- [ ] package to build and deploy Carbon versions
- [ ] API with list of available Carbon versions
- [ ] Inject external files based on user preferences (latest is obviously the default) [documentation](https://developer.chrome.com/apps/app_external)
- [ ] Work with Carbon to auto-detect version
- [ ] Obviously, need some sort of hosting provider, and is there a cost?
